<?php

use Illuminate\Database\Seeder;

class SongNotesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('song_notes')->delete();
        
        \DB::table('song_notes')->insert(array (
            0 => 
            array (
                'id' => 2,
                'song_id' => 153,
                'user_id' => 1,
            'note' => '(Traditional Cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:42:53',
                'updated_at' => '2016-12-12 18:42:53',
                'order' => 0,
            ),
            1 => 
            array (
                'id' => 4,
                'song_id' => 154,
                'user_id' => 1,
            'note' => '<p>(Habershon/Gabriel cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:43:37',
                'updated_at' => '2016-12-12 18:43:37',
                'order' => 0,
            ),
            2 => 
            array (
                'id' => 5,
                'song_id' => 155,
                'user_id' => 1,
            'note' => '<p>(Albert E. Brumley cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:44:27',
                'updated_at' => '2016-12-12 18:44:27',
                'order' => 0,
            ),
            3 => 
            array (
                'id' => 7,
                'song_id' => 159,
                'user_id' => 1,
            'note' => '<p>(Traditional cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:45:02',
                'updated_at' => '2016-12-12 18:45:02',
                'order' => 0,
            ),
            4 => 
            array (
                'id' => 8,
                'song_id' => 34,
                'user_id' => 1,
            'note' => '<p>(Jim Avett cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:45:22',
                'updated_at' => '2016-12-12 18:45:22',
                'order' => 0,
            ),
            5 => 
            array (
                'id' => 10,
                'song_id' => 160,
                'user_id' => 1,
            'note' => '<p><font color="#3a3a3a">(Traditional cover)</font><br></p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:46:00',
                'updated_at' => '2016-12-12 18:46:00',
                'order' => 0,
            ),
            6 => 
            array (
                'id' => 11,
                'song_id' => 227,
                'user_id' => 1,
            'note' => '<p>(John Prine cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:46:26',
                'updated_at' => '2016-12-12 18:46:26',
                'order' => 0,
            ),
            7 => 
            array (
                'id' => 12,
                'song_id' => 283,
                'user_id' => 1,
            'note' => '<p>(Traditional cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:47:16',
                'updated_at' => '2016-12-12 18:47:16',
                'order' => 0,
            ),
            8 => 
            array (
                'id' => 13,
                'song_id' => 310,
                'user_id' => 1,
            'note' => '<p><font color="#3a3a3a">(Thin Lizzy cover)</font><br></p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:49:10',
                'updated_at' => '2016-12-12 18:49:10',
                'order' => 0,
            ),
            9 => 
            array (
                'id' => 14,
                'song_id' => 311,
                'user_id' => 1,
            'note' => '<p>(Roy Rogers cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:49:25',
                'updated_at' => '2016-12-12 18:49:25',
                'order' => 0,
            ),
            10 => 
            array (
                'id' => 15,
                'song_id' => 161,
                'user_id' => 1,
            'note' => '<p>(Doc Watson cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:50:04',
                'updated_at' => '2016-12-12 18:50:04',
                'order' => 0,
            ),
            11 => 
            array (
                'id' => 16,
                'song_id' => 241,
                'user_id' => 1,
            'note' => '<p>(Traditional cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:50:21',
                'updated_at' => '2016-12-12 18:50:21',
                'order' => 0,
            ),
            12 => 
            array (
                'id' => 17,
                'song_id' => 230,
                'user_id' => 1,
            'note' => '<p><font color="#3a3a3a">(David Childers cover)</font><br></p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:50:54',
                'updated_at' => '2016-12-12 18:50:54',
                'order' => 0,
            ),
            13 => 
            array (
                'id' => 18,
                'song_id' => 219,
                'user_id' => 1,
            'note' => '<p>(Traditional cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:51:10',
                'updated_at' => '2016-12-12 18:51:10',
                'order' => 0,
            ),
            14 => 
            array (
                'id' => 19,
                'song_id' => 263,
                'user_id' => 1,
            'note' => '<p>(Traditional cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:51:30',
                'updated_at' => '2016-12-12 18:51:30',
                'order' => 0,
            ),
            15 => 
            array (
                'id' => 20,
                'song_id' => 251,
                'user_id' => 1,
            'note' => '<p>(Traditional cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:51:40',
                'updated_at' => '2016-12-12 18:51:40',
                'order' => 0,
            ),
            16 => 
            array (
                'id' => 21,
                'song_id' => 199,
                'user_id' => 1,
            'note' => '<p>(Tom T. Hall cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:52:01',
                'updated_at' => '2016-12-12 18:52:01',
                'order' => 0,
            ),
            17 => 
            array (
                'id' => 22,
                'song_id' => 262,
                'user_id' => 1,
            'note' => '<p><font color="#3a3a3a">(Buck Owens cover)</font><br></p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:52:16',
                'updated_at' => '2016-12-12 18:52:16',
                'order' => 0,
            ),
            18 => 
            array (
                'id' => 23,
                'song_id' => 274,
                'user_id' => 1,
            'note' => '<p>(Traditional cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:52:32',
                'updated_at' => '2016-12-12 18:52:32',
                'order' => 0,
            ),
            19 => 
            array (
                'id' => 24,
                'song_id' => 195,
                'user_id' => 1,
            'note' => '<p><font color="#3a3a3a">(Lester Flatt &amp; Earl Scruggs cover)</font><br></p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:52:55',
                'updated_at' => '2016-12-12 18:52:55',
                'order' => 0,
            ),
            20 => 
            array (
                'id' => 25,
                'song_id' => 188,
                'user_id' => 1,
            'note' => '<p>(Traditional cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:58:39',
                'updated_at' => '2016-12-12 18:58:39',
                'order' => 0,
            ),
            21 => 
            array (
                'id' => 26,
                'song_id' => 239,
                'user_id' => 1,
            'note' => '<p>(John Denver cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:59:01',
                'updated_at' => '2016-12-12 18:59:01',
                'order' => 0,
            ),
            22 => 
            array (
                'id' => 27,
                'song_id' => 284,
                'user_id' => 1,
            'note' => '<p>(The Spaniels cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:59:21',
                'updated_at' => '2016-12-12 18:59:21',
                'order' => 0,
            ),
            23 => 
            array (
                'id' => 28,
                'song_id' => 216,
                'user_id' => 1,
            'note' => '<p>(Roger Miller cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:59:33',
                'updated_at' => '2016-12-12 18:59:33',
                'order' => 0,
            ),
            24 => 
            array (
                'id' => 29,
                'song_id' => 276,
                'user_id' => 1,
            'note' => '<p>(Traditional cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 18:59:55',
                'updated_at' => '2016-12-12 18:59:55',
                'order' => 0,
            ),
            25 => 
            array (
                'id' => 30,
                'song_id' => 203,
                'user_id' => 1,
            'note' => '<p>(Townes Van Zandt cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:00:19',
                'updated_at' => '2016-12-12 19:00:19',
                'order' => 0,
            ),
            26 => 
            array (
                'id' => 31,
                'song_id' => 265,
                'user_id' => 1,
            'note' => '<p>(Townes Van Zandt cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:00:37',
                'updated_at' => '2016-12-12 19:00:37',
                'order' => 0,
            ),
            27 => 
            array (
                'id' => 32,
                'song_id' => 266,
                'user_id' => 1,
            'note' => '<p>(Traditional cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:00:51',
                'updated_at' => '2016-12-12 19:00:51',
                'order' => 0,
            ),
            28 => 
            array (
                'id' => 33,
                'song_id' => 268,
                'user_id' => 1,
            'note' => '<p><font color="#3a3a3a">(Blaze Foley cover)</font><br></p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:01:06',
                'updated_at' => '2016-12-12 19:01:06',
                'order' => 0,
            ),
            29 => 
            array (
                'id' => 34,
                'song_id' => 317,
                'user_id' => 1,
            'note' => '<p>(Evan Dando cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:38:18',
                'updated_at' => '2016-12-12 19:38:18',
                'order' => 0,
            ),
            30 => 
            array (
                'id' => 35,
                'song_id' => 235,
                'user_id' => 1,
            'note' => '(Doc Watson cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:38:40',
                'updated_at' => '2016-12-12 19:38:40',
                'order' => 0,
            ),
            31 => 
            array (
                'id' => 37,
                'song_id' => 192,
                'user_id' => 1,
            'note' => '<br><p>(Felice and Boudleaux Bryant / The Everly Brothers cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:40:41',
                'updated_at' => '2016-12-12 19:40:41',
                'order' => 0,
            ),
            32 => 
            array (
                'id' => 38,
                'song_id' => 256,
                'user_id' => 1,
            'note' => '(Traditional cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:41:03',
                'updated_at' => '2016-12-12 19:41:03',
                'order' => 0,
            ),
            33 => 
            array (
                'id' => 39,
                'song_id' => 333,
                'user_id' => 1,
            'note' => '(Van Morrison cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:41:30',
                'updated_at' => '2016-12-12 19:41:30',
                'order' => 0,
            ),
            34 => 
            array (
                'id' => 40,
                'song_id' => 242,
                'user_id' => 1,
            'note' => '<p>(Rolling Stones cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:41:55',
                'updated_at' => '2016-12-12 19:41:55',
                'order' => 0,
            ),
            35 => 
            array (
                'id' => 41,
                'song_id' => 282,
                'user_id' => 1,
            'note' => '(Traditional cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:42:56',
                'updated_at' => '2016-12-12 19:42:56',
                'order' => 0,
            ),
            36 => 
            array (
                'id' => 42,
                'song_id' => 202,
                'user_id' => 1,
            'note' => '(Traditional cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:43:40',
                'updated_at' => '2016-12-12 19:43:40',
                'order' => 0,
            ),
            37 => 
            array (
                'id' => 43,
                'song_id' => 295,
                'user_id' => 1,
            'note' => '<p>(Fiddlin John Carson cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:45:30',
                'updated_at' => '2016-12-12 19:45:30',
                'order' => 0,
            ),
            38 => 
            array (
                'id' => 44,
                'song_id' => 228,
                'user_id' => 1,
            'note' => '<p>(John Denver cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:47:25',
                'updated_at' => '2016-12-12 19:47:25',
                'order' => 0,
            ),
            39 => 
            array (
                'id' => 45,
                'song_id' => 214,
                'user_id' => 1,
            'note' => '(Randy Newman cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:49:18',
                'updated_at' => '2016-12-12 19:49:18',
                'order' => 0,
            ),
            40 => 
            array (
                'id' => 46,
                'song_id' => 309,
                'user_id' => 1,
            'note' => '(cover Les Mis)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:49:58',
                'updated_at' => '2016-12-12 19:49:58',
                'order' => 0,
            ),
            41 => 
            array (
                'id' => 47,
                'song_id' => 277,
                'user_id' => 1,
            'note' => '<p>(Jimmie Rodgers cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:50:26',
                'updated_at' => '2016-12-12 19:50:26',
                'order' => 0,
            ),
            42 => 
            array (
                'id' => 48,
                'song_id' => 177,
                'user_id' => 1,
            'note' => '<p>(Donovan cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:50:52',
                'updated_at' => '2016-12-12 19:50:52',
                'order' => 0,
            ),
            43 => 
            array (
                'id' => 49,
                'song_id' => 207,
                'user_id' => 1,
            'note' => '(Donovan cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:51:13',
                'updated_at' => '2016-12-12 19:51:13',
                'order' => 0,
            ),
            44 => 
            array (
                'id' => 50,
                'song_id' => 349,
                'user_id' => 1,
            'note' => '<p>(Tim Spencer / Ramblin Jack Elliott cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:51:50',
                'updated_at' => '2016-12-12 19:51:50',
                'order' => 0,
            ),
            45 => 
            array (
                'id' => 51,
                'song_id' => 293,
                'user_id' => 1,
            'note' => '<p>(Blaze Foley cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:52:33',
                'updated_at' => '2016-12-12 19:52:33',
                'order' => 0,
            ),
            46 => 
            array (
                'id' => 52,
                'song_id' => 307,
                'user_id' => 1,
            'note' => '(Traditional cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:52:56',
                'updated_at' => '2016-12-12 19:52:56',
                'order' => 0,
            ),
            47 => 
            array (
                'id' => 53,
                'song_id' => 226,
                'user_id' => 1,
            'note' => '(Sam Cooke cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:53:22',
                'updated_at' => '2016-12-12 19:53:22',
                'order' => 0,
            ),
            48 => 
            array (
                'id' => 54,
                'song_id' => 55,
                'user_id' => 1,
                'note' => 'Written by Paleface',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:53:46',
                'updated_at' => '2016-12-12 19:53:46',
                'order' => 0,
            ),
            49 => 
            array (
                'id' => 55,
                'song_id' => 322,
                'user_id' => 1,
            'note' => '(Tom Petty cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:54:28',
                'updated_at' => '2016-12-12 19:54:28',
                'order' => 0,
            ),
            50 => 
            array (
                'id' => 56,
                'song_id' => 197,
                'user_id' => 1,
            'note' => '(Traditional cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:54:49',
                'updated_at' => '2016-12-12 19:54:49',
                'order' => 0,
            ),
            51 => 
            array (
                'id' => 57,
                'song_id' => 320,
                'user_id' => 1,
            'note' => '(Traditional cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:55:41',
                'updated_at' => '2016-12-12 19:55:41',
                'order' => 0,
            ),
            52 => 
            array (
                'id' => 58,
                'song_id' => 206,
                'user_id' => 1,
            'note' => '(Jessica Lea Mayfield cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:56:30',
                'updated_at' => '2016-12-12 19:56:30',
                'order' => 0,
            ),
            53 => 
            array (
                'id' => 59,
                'song_id' => 258,
                'user_id' => 1,
            'note' => '(Randy Travis cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:57:08',
                'updated_at' => '2016-12-12 19:57:08',
                'order' => 0,
            ),
            54 => 
            array (
                'id' => 60,
                'song_id' => 319,
                'user_id' => 1,
            'note' => '(Traditional cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:57:58',
                'updated_at' => '2016-12-12 19:57:58',
                'order' => 0,
            ),
            55 => 
            array (
                'id' => 61,
                'song_id' => 158,
                'user_id' => 1,
            'note' => '(Traditional cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:58:44',
                'updated_at' => '2016-12-12 19:58:44',
                'order' => 0,
            ),
            56 => 
            array (
                'id' => 62,
                'song_id' => 179,
                'user_id' => 1,
            'note' => '(Paleface cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:59:07',
                'updated_at' => '2016-12-12 19:59:07',
                'order' => 0,
            ),
            57 => 
            array (
                'id' => 63,
                'song_id' => 270,
                'user_id' => 1,
            'note' => '(Traditional cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:59:21',
                'updated_at' => '2016-12-12 19:59:21',
                'order' => 0,
            ),
            58 => 
            array (
                'id' => 64,
                'song_id' => 313,
                'user_id' => 1,
            'note' => '(Bruce Springsteen cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 19:59:48',
                'updated_at' => '2016-12-12 19:59:48',
                'order' => 0,
            ),
            59 => 
            array (
                'id' => 65,
                'song_id' => 156,
                'user_id' => 1,
            'note' => '(Traditional cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 20:00:18',
                'updated_at' => '2016-12-12 20:00:18',
                'order' => 0,
            ),
            60 => 
            array (
                'id' => 66,
                'song_id' => 301,
                'user_id' => 1,
            'note' => '<p>(Beyoncé Knowles, Ryan Tedder, E. Kidd Bogart cover)<br></p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 20:01:13',
                'updated_at' => '2016-12-12 20:01:13',
                'order' => 0,
            ),
            61 => 
            array (
                'id' => 67,
                'song_id' => 267,
                'user_id' => 1,
            'note' => '<p>(Jason Molina cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 20:01:31',
                'updated_at' => '2016-12-12 20:01:31',
                'order' => 0,
            ),
            62 => 
            array (
                'id' => 68,
                'song_id' => 243,
                'user_id' => 1,
            'note' => '<p>(Stephen Collins Foster cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 20:02:02',
                'updated_at' => '2016-12-12 20:02:02',
                'order' => 0,
            ),
            63 => 
            array (
                'id' => 69,
                'song_id' => 172,
                'user_id' => 1,
            'note' => '(Traditional cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 20:03:12',
                'updated_at' => '2016-12-12 20:03:12',
                'order' => 0,
            ),
            64 => 
            array (
                'id' => 70,
                'song_id' => 209,
                'user_id' => 1,
            'note' => '<p>(Townes Van Zandt cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 20:03:57',
                'updated_at' => '2016-12-12 20:03:57',
                'order' => 0,
            ),
            65 => 
            array (
                'id' => 71,
                'song_id' => 189,
                'user_id' => 1,
            'note' => '<p>(Justin Gordon cover)</p>',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 20:04:21',
                'updated_at' => '2016-12-12 20:04:21',
                'order' => 0,
            ),
            66 => 
            array (
                'id' => 72,
                'song_id' => 238,
                'user_id' => 1,
            'note' => '(Tom T. Hall cover)',
                'published' => 1,
                'type' => 'public',
                'creator_id' => 1,
                'created_at' => '2016-12-12 20:04:59',
                'updated_at' => '2016-12-12 20:04:59',
                'order' => 0,
            ),
        ));
        
        
    }
}
